### ISSUE TITLE
Please provide sample firebase_options.dart and .env

### ISSUE THREAD

**Issue by yakovkeselman** [viscosenpai/social_login_sample#1]
Thanks!

**Comment by viscosenpai** [comment]
firebase_option.dart is a file that is automatically generated using the [flutterfire_cli](https://pub.dev/packages/flutterfire_cli) package.
.env should contain your Twitter API Key and Twitter API Secret Key.

**Comment by yakovkeselman** [comment]
Cool, thanks for the info!
